### ISSUE TITLE
Checkout task Deprecated and Fails

### ISSUE THREAD

**Issue by akhawajaIIC** [jessehouwing/azure-pipelines-tfvc-tasks#112]
Hi,

Yesterday we started to notice our builds failing with the checkout task.  I noticed there were changes checked in just before our pipeline started to fail.  I've tried both v1 and v2 of the task and both fail with different errors (please see attached).  The task also shows as Depreciated in the pipeline.  Your help would be greatly appreciated in resolving these issues.

Regards,
Asim

[tfvc - checkoutv2_6 - error.txt](https://github.com/jessehouwing/azure-pipelines-tfvc-tasks/files/13239061/tfvc.-.checkoutv2_6.-.error.txt)
[tfvc - checkoutv1_6 - error.txt](https://github.com/jessehouwing/azure-pipelines-tfvc-tasks/files/13239062/tfvc.-.checkoutv1_6.-.error.txt)
![tfvc - deprecated](https://github.com/jessehouwing/azure-pipelines-tfvc-tasks/assets/149687101/ad6d421d-db3c-478b-8095-fbdf40b2b5ac)

**Comment by jessehouwing** [comment]
As for the task being deprecated, that's expected for the Check-out task,  Azure Pipelines defaults to local workspaces and explicitly checking out isn't required.

**Comment by akhawajaIIC** [comment]
Sorry, I didn't see the duplicate item logged.  Thank you for the quick response!
