### ISSUE TITLE
Convert to Typescript

### ISSUE THREAD

**Issue by jessehouwing** [jessehouwing/azure-pipelines-tfvc-tasks#43]
Now that Agent 2 is out and it ships with tf.exe on windows and tf on linux I want to convert over to invoking that instead of rolling my own code. That should insure the same behavior and will make the whole system more extensible

 * [ ] Create generic TF task that invokes TF and passes additional arguments and optionally adds the collection and auth information
   * [ ] Windows
   * [ ] Linux (solve any parameter issues)
 * [ ] Convert existing Check-in task
 * [ ] Convert existing Add task
 * [ ] Convert existing Delete task
 * [ ] Convert existing Update Gated Changes task
 * [ ] Convert existing Undo task
 * <s>[ ] Checkout task</s> should not be needed, since the 2.0 agent explicitly always creates a local workspace

From there it should be easy to support

 * [ ] Map additional directories & get
 * [ ] Merge task
 * [ ] Branch task
 * [ ] Download from TFVC task (create workspace, map, get)

**Comment by arman-m** [comment]
This is a great idea but the comment is almost 2 years old. Are you still planning to convert the task to Typescript? I just installed it and I get a warning after build:
##[warning]Task 'TFVCCheckin' (1.4.1) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

**Comment by jessehouwing** [comment]
If you'd pick the 2.* version of the task the warning will disappear.

I have few clients using tfvc at the moment, so not very many victims to
test against. Thus trying to not do too much high impact changes.

What would you use a typescript version for?
