### ISSUE TITLE
'TFVC - Check-in changes' not finding changed files

### ISSUE THREAD

**Issue by smoeller-liveid** [jessehouwing/azure-pipelines-tfvc-tasks#52]
Hello, during my build, I update a few files with current version number, and store e.g. WiX file ID's. These files I'd like to check in after build. This means I know exactly the files to check in (full path)
But I cannot get the check-in task to work. I always receive the error from the script "System.Management.Automation.MethodInvocationException: Exception calling "GetPendingChanges" with "2" argument(s): "Illegal characters in path." ---> System.ArgumentException: Illegal characters in path."
I think this is because the script does not properly split what I have entered into 'Files to check in'
Some example:
If I put below into 'Files to check in':
$(Build.SourceBranch)/foo/bar.wxi
$(Build.SourceBranch)/bar/version.xml
The debug log shows:
2017-09-20T08:03:44.4893416Z $/source/V1.6/foo/bar.wxi
2017-09-20T08:03:44.4893416Z 
2017-09-20T08:03:44.4893416Z 
2017-09-20T08:03:44.4893416Z $/source/V1.6/bar/version.xml
See the two empty lines? I think this is where the "Illegal characters in path" error comes from.
And when I input not in separate lines, but with ";", I still get
2017-09-20T08:03:44.4893416Z $/source/V1.6/foo/bar.wxi
2017-09-20T08:03:44.4893416Z ;
2017-09-20T08:03:44.4893416Z $/source/V1.6/bar/version.xml
So, the separator gets into the list. 

What am I doing wrong here?

B.t.w., I also one input just 
$(Build.SourceBranch)/*.*
but then I see in the log that no files for checkin are found. But if I start the next build, the new log shows that pending changes on exactly my files have been undone, so the files have been checked out.
_*Edit*
The wildcard version above does work, I just forgot to select the correct "Recursion" mode._

I think I missed something, but what?

Any help appreciated, Sebastian

**Comment by jessehouwing** [comment]
Have you tried `Build.SourcesDirectory` instead of `Build.SourceBranch`?
