### ISSUE TITLE
"I understand" checkbox isn't required 

### ISSUE THREAD

**Issue by ChrisMenegay** [jessehouwing/azure-pipelines-tfvc-tasks#64]
though message indicates it is, I missed seeing it and my stuff checked in fine, but I did get a powershell error in my build log. The comment on the task help probably just needs to be updated.

**Comment by jessehouwing** [comment]
Ohh yeah. Problem is, setting it required doesn't make it required to be
true. So the Ui happily submits false.

**Comment by ChrisMenegay** [comment]
Can't you see that it is false and just immediately throw an error, rather than doing the checkin?
