### ISSUE TITLE
how to check out all the Assembly info files using pattern recursively

### ISSUE THREAD

**Issue by harishchepuri** [jessehouwing/azure-pipelines-tfvc-tasks#67]
how to check out all the Assembly info files using pattern recursively

**Comment by jessehouwing** [comment]
It follows the same pattern as tf.exe.

Though you shouldn't have to check them out, the 2.x agent uses local
workspaces. If you're still on agent 1.x it's really really time to
upgrade.

I suspect the pattern is `assembly.cs` and then check the recursive
checkbox.

**Comment by jessehouwing** [comment]
Just uninstall the 1.x agent and then install the 2.x agent. Your tfs/vsts
service should offer the download link to its latest supported version.

**Comment by harishchepuri** [comment]
I uninstalled and installed still its showing as 1.0

**Comment by jessehouwing** [comment]
Task or agent?

**Comment by harishchepuri** [comment]
Task

**Comment by jessehouwing** [comment]
Checkout is only needed when using the 1.x agent and a server workspace.
And is officially not even supported

In all other cases, just overwrite the files.

**Comment by harishchepuri** [comment]
what is this 2.x agent

**Comment by jessehouwing** [comment]
Ok, I'll need a better report.

What are you using?
* TFS, which version
* VSTS

What agent are you using?
* VSTS hosted agent, which pool?
* Self hosted agent, which version (check the agent queue)

What is the default workspace setting of the
* Team Project
* Team Project Collection

In most cases you won't need to use the Checkout task. The checkout task is
only needed when you are using:

* TFS 2015
* VSTS Agent 1.83 ~ 1.95
* Team Project Collection default setting

https://docs.microsoft.com/en-us/vsts/repos/tfvc/decide-between-using-local-server-workspace?view=vsts#manage-project-collection-workspace-settings-for-your-team

In all other cases the build agent will create a local workspace and using
that the files are automatically checked out.

If you're still using this configuration it's highly recommended to upgrade
to a more recent version of TFS, in which case you'll be able to use the
2.x build agent and won't need to use the checkout task either.

**Comment by jessehouwing** [comment]
I'd try one if the following:

 * multiple checkout tasks that check out a set of files each. Then one
checkin task.
* don't use the checkout task, and use a checkin task configured to detect
changes automatically


I suspect I may be able to extend the length if the input box... But I'm
not sure I want to. The checkout task is really a temporary solution for a
few people using tfs 2015. On the vsts agent it should be a no-op. And
won't actually lock anything.

**Comment by harishchepuri** [comment]
i updated the assembly info class and when i am trying to checkin it showing message **no changes to checkin** ,i cross checked the build working folder and i am able to see changes , any idea about this why its showing above message
