### ISSUE TITLE
Not working on 32bit

### ISSUE THREAD

**Issue by shayki5** [jessehouwing/azure-pipelines-tfvc-tasks#77]
Hi :)
We have some builds that tunning on 32bit, the tasks not working there.
Can you please add support to 32bit?
Thank you so much!

**Comment by jessehouwing** [comment]
I don't see why they wouldn't be working there. What errors are you
getting? Does the agent even support 32 bits nowadays?

**Comment by shayki5** [comment]
Yes, there is a special agent for 32 bits.
I got an error:
"A supported task execution handler was not found. The task does not carry an implementaion that is compatible with your current operating system 'Windows (x86)'. Contact the task author for more deails".
Thanks again!

**Comment by jessehouwing** [comment]
I'm guessing the task itself would need no changes. Just an extra handler,
but I don't have any 32 systems to test with.

I'll see what I can do in the near future.

**Comment by shayki5** [comment]
Ok, thank you so much!
Do you have any idea where the handler should be? maybe I can add it myself.

**Comment by jessehouwing** [comment]
At the bottom of each task.json.

**Comment by jessehouwing** [comment]
Got some more details and to solve this the task must be upgraded to the PowerShell3 handler or Typescript. This has been long in the plans, but it's still pretty far off.

**Comment by shayki5** [comment]
Ok, thank you so much for your response!!

**Comment by shayki5** [comment]
Hi,
Just update... I needed it pretty urgent (build need to be passed... )so I wrote some tasks myself :)
So you can wait ;)
Thank you again!

**Comment by jessehouwing** [comment]
Why no pull request ;)

**Comment by shayki5** [comment]
Because I just wrote a small PowerShell script... I didn't adjust your tasks...

**Comment by jessehouwing** [comment]
Added a PS3 handler. This should be fixed now.
