### ISSUE TITLE
Check in does not recognize replaced files

### ISSUE THREAD

**Issue by bcbuddy** [jessehouwing/azure-pipelines-tfvc-tasks#82]
I have a build process that updates a database backup(.bak) that sits in my project. I was hoping to use the check-in task to check the file back into source control after an update but it seems that no changes get recognized. 

It would be nice if there was a "force" option for replacing these kinds of files.

**Comment by jessehouwing** [comment]
Have you tried using the tfvc add task for that?

I'd expect your `.tfignore` file is blocking the add action, it's probably best to add an exclusion for your database backup folder.

Just add a extra tf ignore file in that folder and add `!*.bak`

**Comment by jessehouwing** [comment]
There was a bug introduced when using the latest agent version. I fixed that.
