### ISSUE TITLE
Check-in and null checkedWorkItems

### ISSUE THREAD

**Issue by danielstefanescu** [jessehouwing/azure-pipelines-tfvc-tasks#87]
Hi,
Any reason in passing null as $checkedWorkItems in [TfvcCheckin.v3.ps1](https://raw.githubusercontent.com/jessehouwing/azure-pipelines-tfvc-tasks/master/tf-vc-checkin/v2/TfvcCheckin.v3.ps1) line 245?

**Comment by jessehouwing** [comment]
What else would you have me pass in there? It's a pretty fuzzy business, should I attach the same items as the last checkin? Since the last successful build? None, cause the changes made by the build aren't linked to the work? Always the same?

So, for now, I choose to simply pass in null.
