### ISSUE TITLE
.dll files are ignored in Check-in

### ISSUE THREAD

**Issue by vcb-xrmvision** [jessehouwing/azure-pipelines-tfvc-tasks#90]
We use this really usefull build task to check-in Dynamics 365 solution that sometime contains assemblies .dll file but the tfvc task ignore thoses files. Is there a way to avoid this behaviour? I understand that in a normal case it's a desired behaviour but not in the specific use case we are using it.

Thanks

**Comment by jessehouwing** [comment]
Have you set `Apply Localitem Exclusions` to false?

**Comment by vcb-xrmvision** [comment]
I'm using the task from the DevOps UI and the setting "Apply Localitem Exclusions" dosen't seem to be exposed in the UI,[
![tfvs_checkin_settings](https://user-images.githubusercontent.com/58830932/70755233-43efff80-1d07-11ea-9d6e-1f5c2eee5227.png)
](url)

**Comment by jessehouwing** [comment]
Use the tfvc add task to stage the explicitly

**Comment by vcb-xrmvision** [comment]
Excellent! thanks it solved my issue
