### ISSUE TITLE
Not able to update a DLL.

### ISSUE THREAD

**Issue by NehaaSinghh** [jessehouwing/azure-pipelines-tfvc-tasks#93]
Hi, 
I am trying to update a DLL in TFS on successful completion of a build pipeline. But DLLs do not get identified as edited when we replace old DLL with the new one.
So I am following below steps to accomplish this task-
1. Delete old dll i.e. add as deleted in the pending changes.
2. Check-in the change.
3. Copy new DLL to the mapped folder.
4. Add file to pending changes.
5. Check-in the changes.

The issue is it either adds the new file to TFS or deletes existing one. I want both the operations to be done after every build. 
PFA for the log files. This time it already has the DLL on TFS so it is deletes it perfectly but while adding the new one it throws  "_**[warning]The item ************************ already exists.**_"-
[Logs.zip](https://github.com/jessehouwing/azure-pipelines-tfvc-tasks/files/3997694/Logs.zip)

Thanks!

**Comment by jessehouwing** [comment]
Any specific reason you commit the delete first? Why not simply overwrite the file?

Right now you're basically doing a "restore" and I'm not sure how the powershell code interacts with the "do you want to restore history for this item?" prompt that I thing you'd get when using tf.exe.

I haven't tested this scenario before. I may be able to work around this after the holidays.

For now, I'd remove the "2. Check-in change" step. It serves no real purpose anyway.

**Comment by jessehouwing** [comment]
Check: https://github.com/jessehouwing/azure-pipelines-tfvc-tasks/issues/90

It explains how to detect the pending change on the dll file. These extensions are excluded by default.

It would be even better to add a `.tfignore` file to your specific folder to allow .dll files.

e.g.:

$/Decos Menuet/MenuetSettingsRenaming/Binaries/.tfignore
```
!*.dll
```

PS it looks like you're on the 1.x version of the task. I highly recommend updating to 2.x.
