### ISSUE TITLE
Checkin V2 task doesn't support custom author (but task.json has them)

### ISSUE THREAD

**Issue by jpricket** [jessehouwing/azure-pipelines-tfvc-tasks#95]
The Checkin V1 task works perfectly. So, I was very confused when the V2 task didn't set author correctly. Until I finally looked at the code. The author parameters are not passed in or used.

**Comment by jessehouwing** [comment]
Good catch. Wonder how that slipped through. Will push a fix soon.

**Comment by jessehouwing** [comment]
Or if you can do a PR, I'd be happy to accept it sooner.

**Comment by jessehouwing** [comment]
https://github.com/jessehouwing/azure-pipelines-tfvc-tasks/blob/features/customauthor/tf-vc-checkin/v1/TfvcCheckin.ps1
