### ISSUE TITLE
Gated Check-in fails while checking in gated changes while other tasks succeed

### ISSUE THREAD

**Issue by Prateek1584990** [jessehouwing/azure-pipelines-tfvc-tasks#98]
Hi,
While trying to check-in the code the build fails at 'check in gated changes' step with the error:
The shelveset _Build_55;Build\54765f06-3a38-4a0a-9813-79a9da79a93f could not be found for check-in.
Could not find any resolution for this.
Please find the logs attached. Please help in resolving this ASAP. Let us know if any other information may be required.[https://developercommunity.visualstudio.com/content/problem/901131/gated-check-in-fails-while-checking-in-gated-chang.html](url)
[116302-logs-57.zip](https://github.com/jessehouwing/azure-pipelines-tfvc-tasks/files/4147262/116302-logs-57.zip)

**Comment by jessehouwing** [comment]
> Please help in resolving this ASAP.

I'm sorry, but this is an open-source volunteer maintained task.  I can't be compelled to act immediately. 

----

That said, welcome to the TFVC tasks project, I'd love to help out if I can, but I'd need more information:

 * TFS/Azure DevOps version
 * Agent version
 * Extension version in use
 * Task version in use (v1|v2)
 * A diagnostics log of the task

Unfortunately, I can't access the attachment on the developer community, can you attach it here? If possible, can you run the following bit of powershell?

```
$collection="https://dev.azure.com/jessehouwing-dev/"
([xml] $( tf vc shelvesets /collection:$collection /format:xml /owner:*)) | %{$_.Shelvesets.Shelveset} | ?{[string]$_.name -like "Gated*" -and $_.owner -like "Build*"}
```

**Comment by jessehouwing** [comment]
But what it looks like, is that the build isn't running a Gated build, but a manual or CI build instead.

**Comment by Prateek1584990** [comment]
[116302-logs-57.zip](https://github.com/jessehouwing/azure-pipelines-tfvc-tasks/files/4151913/116302-logs-57.zip)
Hi Jesse, thank you for your response. You might have missed, however I had attached the build logs in my initial request itself. Attaching them again. 

TFS/Azure DevOps version - latest
Agent version - running on Azure pipelines (Current agent version: '2.164.6')

**Comment by jessehouwing** [comment]
I don't see the task being executed at all in this phase. Can you share the actual build definition?

**Comment by Prateek1584990** [comment]
![image](https://user-images.githubusercontent.com/49140360/73845384-838b2180-4848-11ea-8a15-dc5332802d00.png)

**Comment by jessehouwing** [comment]
That's not **my** check-in gated changes task. Sorry, I'm going to have to send you back to Microsoft.
